#config spring boot reactive mongodb
server:
    port: 8091
spring:
    mongodb:
        embedded:
            version: 3.6.2
    data:
        mongodb:
            database: productdb
            host: localhost
            port: 27017
#            username: root
#            password: root